### ISSUE TITLE
But make it really more usable, right?

### ISSUE THREAD

**Issue by xzj8b3** [manatools/dnfdragora#120] opened 2018-11-04 13:58 UTC
Really slow and not very detailed

No confirmation messages about the operation performed (not even notify the result of an installation or other details)

very little in the search packages, dnf much more effective

**Comment by anaselli** [comment] 2018-11-04 22:18
thanks for the report. Unfortunately it isn't that much useful to understand which the problem is and so there is not so much i can do for fixing it, sorry. Closing

**Closed by anaselli** 2018-11-04 22:18 UTC

**Comment by xzj8b3** [comment] 2018-11-05 11:08
> grazie per la segnalazione Sfortunatamente non è molto utile capire quale sia il problema e quindi non c'è molto che possa fare per risolverlo, mi dispiace. Chiusura

The problem is that using GUI not even this returns messages of success or failure of the installation is being carried out... I think it should be a little more complete and detailed as a tool, also to facilitate new users.... so it's just Poor even in the search for packages that provide very few details!!!

**Comment by yurchor** [comment] 2018-11-05 11:34
> > grazie per la segnalazione Sfortunatamente non è molto utile capire quale sia il problema e quindi non c'è molto che possa fare per risolverlo, mi dispiace. Chiusura
> 
> The problem is that using GUI not even this returns messages of success or failure of the installation is being carried out... I think it should be a little more complete and detailed as a tool, also to facilitate new users.... so it's just Poor even in the search for packages that provide very few details!!!

This is not an appropriate attitude.

Please create separate reports for all your troubles. One for the messages that can be useful, one for the report details that you need, etc. It is impossible to handle this bug report in the current form. We have no need for the reports like "This is crap! Your software sucks!" especially if this is not true at all.
