### ISSUE TITLE
dnfdragora 2.1.2 starts the app window with 0 width

### ISSUE THREAD

**Issue by kreaninw** [manatools/dnfdragora#207] opened 2022-07-31 02:22 UTC
As the title said. I installed the app on Fedora 36, GNOME 42.3, via GNOME Software.

If I am lucky, the app's windows stripe will not show at the edge of the screen. Otherwise, it would be impossible to resize the window, thus it's impossible to use the app at all. The issue is shown in the screen recording below:

[Kooha-07-30-2022-22-11-59.webm](https://user-images.githubusercontent.com/1403194/182006899-016e6933-6d87-487d-8016-06dd3ed3bd69.webm)

**Comment by anaselli** [comment] 2022-07-31 11:35
I don't have gnome so i cannot testi right now. 
Can you please make two tests?

1. run dnfdragora from console and see if it works or write something
2. run dnfdragora with --fullscreen option and see if it works (in such a case a workaround could be to change the desktop file)

**Comment by LazyT** [comment] 2022-09-11 10:09
Same here with Fedora 36:

`
<ERR> [Gdk] libyui-gtk:0 (): gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
<ERR> [Gdk] libyui-gtk:0 (): gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
<ERR> [Gdk] libyui-gtk:0 (): gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
<ERR> [Gdk] libyui-gtk:0 (): gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
<ERR> [Gtk] libyui-gtk:0 (): gtk_window_resize: assertion 'width > 0' failed
<_M_> [mga-gtk-ui] YMGA_GCBTable.cc:439 YMGA_GCBTable():  columns 8 tot 8
(python3:6750): Gtk-WARNING **: 11:50:05.922: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node headerbar, owner GtkHeaderBar)
(python3:6750): Gtk-WARNING **: 11:50:05.923: gtk_widget_size_allocate(): attempt to allocate widget with width -102 and height 19
(python3:6750): Gtk-WARNING **: 11:50:05.923: Negative content width -23 (allocation 1, extents 12x12) while allocating gadget (node label, owner GtkLabel)
(python3:6750): Gtk-WARNING **: 11:50:05.959: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node headerbar, owner GtkHeaderBar)
(python3:6750): Gtk-WARNING **: 11:50:05.959: gtk_widget_size_allocate(): attempt to allocate widget with width -102 and height 19
(python3:6750): Gtk-WARNING **: 11:50:05.959: Negative content width -23 (allocation 1, extents 12x12) while allocating gadget (node label, owner GtkLabel)
`

Works fine with "--qt" / "--ncurses" or " --fullscreen".

Switched to Qt in the desktop file as workaround.

**Comment by anaselli** [comment] 2022-09-11 10:26
Thanks for the error, at least i can try to figure where the problem could be...

**Comment by anaselli** [comment] 2022-09-18 13:13
Is DISPLAY variable set in your environment? I read here and there that could be the cause... i know it isn't a solution but another workaround maybe yes...

**Comment by LazyT** [comment] 2022-09-18 13:37
Yes, it is set to "DISPLAY=:0"

**Comment by anaselli** [comment] 2022-09-25 17:15
i committed a patch for [libyui-gtk](https://github.com/anaselli/libyui-gtk/tree/get_working_area) that seems to work, is there anyone who can confirm it so that i ask for a PR? Thanks

**Comment by anaselli** [comment] 2022-09-30 17:41
with the above libyui-gtk commit and https://github.com/manatools/dnfdragora/commit/f42fdf5aaf40aec34fc8ab86fdc6aeb3fd207518 this bug should be fixed.

**Closed by anaselli** 2022-09-30 17:41 UTC

**Comment by liukliukliuk** [comment] 2023-01-14 14:41
can anyone pls tell me how to fix it?

**Comment by anaselli** [comment] 2023-01-14 23:35
Ask your distro for libyui-gtk  and dnfdragora updates
