### ISSUE TITLE
there is no games category

### ISSUE THREAD

**Issue by Spike1377** [manatools/dnfdragora#231] opened 2024-03-31 09:39 UTC
there should be a games category in the applications category

**Comment by anaselli** [comment] 2024-03-31 17:50
Which distribution are you using? Mageia has it. 
In any cases it groups or comps are not under dnfdragora control, but under the distribution.
Using fedora and dnf5 i can see it.

**Comment by Spike1377** [comment] 2024-03-31 22:39
Fedorea

**Comment by anaselli** [comment] 2024-04-01 08:39
```
cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)

```
```
dnf group list --hidden 
Ultima verifica della scadenza dei metadati: 0:00:44 fa il lun 1 apr 2024, 10:35:58.
Gruppi disponibili:
   Sistema Operativo Personalizzato Fedora
   Installazione minima
   Fedora Server
   Fedora Workstation
   Fedora Cloud Server
   Desktop Xfce
   Phosh Desktop
   Desktop LXDE
   Desktop LXQt
   Desktop Cinnamon
   Desktop MATE
   Ambiente desktop Sugar
   Deepin Desktop
   Budgie Desktop
   Workstation di Sviluppo e Creativa
   Server Web
   Server per infrastrutture
   Desktop base
   i3 desktop
   Sway Desktop
Gruppi installati:
   Spazi di lavoro Plasma per KDE
Gruppi installati:
   Strumenti di amministrazione
   Strumenti di Anaconda
   base-x
   Core
   Supporto connesioni remote dial-up
   Browser web Firefox
   Font
   GNOME
   Agenti Desktop per Guest
   Supporto hardware
   Metodi di input
   Applicazioni KDE
   KDE
   Supporto multimediale per KDE
   LibreOffice
   Multimedia
   Sottomoduli comuni di NetworkManager
   Supporto stampa
   Standard
Gruppi disponibili:
   Stampa 3D
   Produzione Audio
   Redazione ed Editoria
   Desktop base
   Budgie
   Budgie Desktop Applications
   Gruppo per la creazione di buildsystem
   Librerie e strumenti di sviluppo in C
   Cinnamon
   Bootloader tools for Cloud images
   Infrastruttura Cloud
   Strumenti di Gestione Cloud
   Strumenti per Server Cloud
   Compiz
   Gestione Container
   Critical Path (anaconda)
   Critical Path (Applicazioni)
   Critical Path (di base)
   Critical Path (Build)
   Critical Path (Compose)
   Critical Path (Deepin desktop)
   Critical Path (GNOME)
   Critical Path (KDE)
   Critical Path (LXDE)
   Critical Path (LXQt)
   Critical Path (Server)
   Critical Path (standard)
   Critical Path (Xfce)
   Strumenti di Sviluppo e Librerie per D
   Deepin Desktop Environment
   Deepin Desktop Applications
   Media packages for Deepin Desktop
   Deepin Desktop Office
   Design Suite
   Librerie di sviluppo
   Strumenti di sviluppo
   Directory Server
   Server dei nomi DNS
   Dogtag Certificate System
   Dominio di Appartenenza
   Editor
   Programmi educativi
   Laboratorio elettronico
   Scientifici e tecnici
   Enlightenment
   Packager Fedora
   Design e pacchettizzazione font
   Server FreeIPA
   Server FTP
   Giochi e svago
   Giochi extra per il Desktop GNOME
   Sviluppo applicativi GNOME
   Applicazioni Internet grafiche
   Grafica
   Agenti guest
   Alta Disponibilità
   HAProxy
   Haskell
   Gestione Headless
   i3 window manager
   i3 window manager (supplemental packages)
   Java
   Programmazione Java
   Server per Applicazioni Java
   Applicazioni didattiche per KDE
   Office per KDE
   Sviluppo applicazioni KDE
   Telepathy per KDE
   Strumenti di Sviluppo KDE Frameworks 5
   Font legacy
   Server di rete legacy
   Sviluppo LibreOffice
   Equalizzatore di carico
   Applicazioni per il desktop LXDE
   LXDE
   Supporto multimediale per LXDE
   Office per LXDE
   Applicazioni per il Desktop LXQt
   LXQt
   Translations of LXQt
   Supporto multimediale per LXQt
   Office per LXQt
   Server mail
   Applicazioni MATE
   MATE
   Milkymist
   MinGW multi-compilatore
   MongoDB
   Database MariaDB (MySQL)
   Server di rete
   Neuron Modelling Simulators
   Server news
   OCaml
   Ufficio/Produttività
   Sviluppo Perl
   Per per il Web
   A phone/tablet UX environment
   PHP
   VMware Platform Support
   Python Classroom
   Python Science
   Robotica
   Strumenti di Sviluppo RPM
   Ruby
   Ruby on Rails
   Laboratorio di Sicurezza
   Strumenti di sistema
   Supporto Hardware per Sistemi Server
   Cuore del sistema Fedora Server 
   File server Windows
   Audio e video
   Database PostgreSQL
   Attività aggiuntive per Sugar
   Ambiente desktop Sugar
   Sway Window Manager
   Sway Window Manager (supplemental packages)
   Strumenti di sistema
   Applicazioni Internet in modalità testo
   Tomcat
   Vagrant con supporto libvirt
   Virtualizzazione
   Virtualizzazione Headless
   Web server base
   Window manager
   Fedora Workstation ostree support
   Cuore del sistema Fedora Workstation
   Sviluppo applicazioni X
   Applicazioni per il Desktop Xfce
   Xfce
   Plugin aggiuntivi per il pannello Xfce
   Supporto multimediale per Xfce
   Office per Xfce
   Svilippo Software per Xfce
   XMonad
   XMonad per MATE
```

No games group is present using dnf4 the problem is not in dnfdragora, sorry. Closing this bug

**Closed by anaselli** 2024-04-01 08:39 UTC

**Comment by Spike1377** [comment] 2024-04-02 05:38
Never knew the categories were from dnf, thanks for telling me thats intresting
