### ISSUE TITLE
GTK gui: remember the window state and size

### ISSUE THREAD

**Issue by nekohayo** [manatools/dnfdragora#175] opened 2020-11-17 19:15 UTC
Everytime I launch the app, it starts maximized, which looks bad and makes no sense on an ultrawide display. Instead, it should be windowed by default and remember the last (un)maximized state and window dimensions, and restore that on startup.

**Comment by anaselli** [comment] 2020-11-18 07:44
I think that came from some changes in [libyui-gtk](https://github.com/libyui/libyui-gtk) but i didn't investigate that much since that is not the dnfdragora core

**Comment by elFarto** [comment] 2021-01-09 09:45
I've noticed the same thing too. I did see this in the output when starting it from the console:

```
<ERR> [Gtk] libyui-gtk:0 (): gtk_window_set_default_size: assertion 'width >= -1' failed
<ERR> [Gtk] libyui-gtk:0 (): gtk_window_resize: assertion 'width > 0' failed
```
Which means displayWidth and displayHeight are returning garbage values. I do have a multi-monitor setup, which maybe what is confusing it.

**Comment by anaselli** [comment] 2021-01-09 11:41
@elFarto don't think it's your multimonitor setup, since i have that error too. I had to work on libyui synching, but i'm going to investigate that more soon, I mean finding which widget is giving that error and see if it is related to this issue too.

**Comment by anaselli** [comment] 2021-01-23 12:08
> <ERR> [Gtk] libyui-gtk:0 (): gtk_window_set_default_size: assertion 'width >= -1' failed
> <ERR> [Gtk] libyui-gtk:0 (): gtk_window_resize: assertion 'width > 0' failed
> Which means displayWidth and displayHeight are returning garbage values. I do have a multi-monitor setup, which maybe what is confusing it.

I got that the [code here](https://github.com/libyui/libyui-gtk/blob/master/src/YGUI.cc#L620-L650) returns -80 for both. Though avoid that code windows does not start in full screen but cannot be reduced by height anyway (see #164).
Failing c++ example is in [libyui/example](https://github.com/libyui/libyui/blob/master/examples/ManyWidgets.cc) since that error is given by **createMainDialog**.
I would move discussion in libyui-gtk and if anyone can help is welcome.

**Comment by anaselli** [comment] 2021-02-03 19:29
i seem i can't reduce the size too much in height, i tried without luck to understand where the problem is. Combobox and list box iirc cannot be reduced (gtk only) and maybe some other widgets too so i suspect a sum of min size required there...
Anyway the patch anaselli/libyui-gtk@ec68394 seems to fix the full screen size start up.

I'll close this one, size cannot be remember using libyui, and full screen start up with that patch seems to be fixed

**Closed by anaselli** 2021-02-03 19:29 UTC
