### ISSUE TITLE
No "Update Notification" after upgrading to dnfdragora version 1.1.1

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#130] opened 2019-02-01 11:46 UTC
Hi. I'm on Fedora 28 X64 bit Cinnamon edition. I recently received version 1.1.1
Since I upgraded to version 1.1.1 , "Update Notification" stop completely !

Before version 1.1.1, I was NOT notified about new updates from 3rd party external repositories such as RPMFusion, so that when their was update for vlc only it gave me no any notification about it. But I was notified regularly about new updates from official Fedora repositories.

But now it seem that notification about new updates failed completely for all repositories !

Other notes: 
1) dnfdragora updater icon is always appearing in Cinnamon panel since I received version 1.1.1
2) when I right-click dnfdragora-updater icon within my DE panel, then click on "Check for update" no thing will happened at all ! I tested this in 2 cases: when there is already updates available & when no any updates available. In both cases, results were the same: no thing happened.

**Comment by anaselli** [comment] 2019-02-10 17:56
Well @Conan-Kudo probably neither a dnfdragora one is. It depends on how it is a 3rd party repository configured, but certainly dnfdaemon is the one that allows dnfdragora and updater to know if there are any updates... am i wrong?

**Comment by Nokia808** [comment] 2019-02-10 19:15
Hi. I did the following:
1) right click on updater icon then click exit,
2) opened terminal,
3) run:
dnfdragora-updater
the updater launched & it's icon re-appeared in panel of DE. but I had the following error output in terminal:

$ dnfdragora-updater
Skipped exception: <[Errno 2] No such file or directory: './dnfdragora.yaml'> 
Icon: /usr/share/icons/hicolor/128x128/apps/dnfdragora.png

What this mean ? And is this the right way to kill updater & run it again from terminal ? If not please give me exact commands one by one.

Thank you for your responses !

**Comment by szaszaiz** [comment] 2019-02-18 23:52
I have the same issue since upgrading to dnfdragora 1.1.1 on Fedora 28 (64-bit) with Cinnamon 4.0.8. The related entry in .xsession-errors:
ERROR:dbus.connection:Unable to set arguments ('dnfdragora-updater', 0, 'dnfdragora', 'dnfdragora', '14 updates available.', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list

Since it only occurs occasionally I can't provide further details on how to reproduce it. Never happened with previous (1.0.1) version.

**Comment by anaselli** [comment] 2019-02-21 06:12
@Conan-Kudo API changed maybe?

**Comment by Nokia808** [comment] 2019-06-02 08:20
Hi. I upgrade my Fedora 28 to 30 & this issue never fixed ! It is still existing on Fedora 30 ! Kindly your attention for it ........

**Comment by anaselli** [comment] 2020-05-30 14:55
dnfdragora-update icon is now always on due to some unwanted behaviors i mentioned on issue #150. If you refere to "update message" shown when there are updates instead, pleas test new 2.02

**Comment by Nokia808** [comment] 2020-06-17 08:02
@anaselli 
I'm already removed dnfdragora from my system because it's bugs are long standing & became useless to me. Moreover, the currently available version in official Fedora repositories is up to version 2.0.0 so that I can not test new changes at this time.

Kindly, give attention for other bugs that still not fixed since years, specially those related to unability of dnfdragora to show 3rd party repositories like RPMFusion repositories & new update from them.

**Comment by anaselli** [comment] 2020-06-17 16:06
That should be fixed too. But i cannot and 2.0.0 should already have it. I cannot force Fedora to update, but i'm trying to release often so that bugs are fixed asap.
Anyway years are nothing compared ages :) and I'm doing my best, time is a variable very hard to find so I'm sorry you removed dnfdragora, but i cannot feel guilty... sorry.

**Comment by anaselli** [comment] 2020-06-17 17:51
dnfdragora 2.0.x has introduced the update concept also to new version to install that yumex-dnf had not, so that is fixed since 2.0.0.
Tryed with skypeforlinux, megasync and rpmfusion

**Closed by anaselli** 2020-06-17 17:51 UTC
