### ISSUE TITLE
dnfdragora-updater: frequent crashes on Fedora

### ISSUE THREAD

**Issue by Woi** [manatools/dnfdragora#140] opened 2019-09-16 21:28 UTC
I like to bring a downstream bug to you attention:
> [abrt] dnfdragora-updater: poll_for_event(): python3.7 killed by SIGABRT
https://bugzilla.redhat.com/show_bug.cgi?id=1667903

First reported in January 2019, it already has 46 observers and 25 duplicates.

**Comment by Conan-Kudo** [comment] 2019-09-23 02:07
Yeah, we're aware of the issues. There's a hack patch by OpenMandriva to sidestep it, but @anaselli  is also prototyping a rework of the application to completely resolve this issue.

It's quite difficult to fix, as we're trying to juggle Python, libyui, and the UI library's thread models...

**Comment by Woi** [comment] 2019-09-28 21:29
Ah... good to hear that this bug is known and being worked on.
When you make a decision about when and how this is fixed, please consider that dnfdragora is used by a lot of non-technical users, which get confused, annoyed or even loss faith in the reliability of "Linux".

**Comment by anaselli** [comment] 2019-09-29 06:39
Unfortunately we cannot do more sorry. But contributions are always welcome

**Comment by Woi** [comment] 2019-09-29 14:01
Why not merge the "hack patch by OpenMandriva", as a temporary workaround till the rework is done?
BTW: Where can I find the patch?

**Comment by anaselli** [comment] 2019-09-29 17:15
> Why not merge the "hack patch by OpenMandriva", as a temporary workaround till the rework is done?
Because that is not a solution but a workaround, and i think, but that is my opinion, it is up to distros decide to add it or not. Moreover we didn't receive it from anyone... 
> BTW: Where can I find the patch?
I think you can get it from openmandriva srpm

**Comment by ckujau** [comment] 2019-12-10 03:30
Meanwhile, [RH# 1667903](https://bugzilla.redhat.com/show_bug.cgi?id=1667903 "dnfdragora-updater: poll_for_event(): python3.7 killed by SIGABRT") has been closed (EOL) but a new bug [RH# 1705076](https://bugzilla.redhat.com/show_bug.cgi?id=1705076 "dnfdragora-updater: poll_for_event(): python3.7 killed by SIGABRT") was opened in May 2019 with over 100 reporters now.

In [dnfdragora.spec](https://github.com/OpenMandrivaAssociation/dnfdragora/blob/master/dnfdragora.spec "dnfdragora/dnfdragora.spec") there are a 5 patches mentioned and I assume with "hack patch by OpenMandriva" [Patch2](https://github.com/OpenMandrivaAssociation/dnfdragora/blob/master/dnfdragora-workaround-for-crashes.patch "Patch2: dnfdragora/dnfdragora-workaround-for-crashes.patch") ("dnfdragora-workaround-for-crashes.patch") is meant - but that seems to deal with [RH# 1505587](https://bugzilla.redhat.com/show_bug.cgi?id=1505587 "YLabel::setValue(): python3.6 killed by SIGSEGV") which is already closed and dealt with a different issue. Here, the crashing function was always `YLabel::setValue` while the still-open [RH# 1705076](https://bugzilla.redhat.com/show_bug.cgi?id=1705076 "dnfdragora-updater: poll_for_event(): python3.7 killed by SIGABRT") is citing `poll_for_event` as the problematic function.

So, the "hack patch by OpenMandriva" may not even help here, I'm afraid :-/ @anaselli any more ideas? :-D

**Comment by Conan-Kudo** [comment] 2019-12-10 03:32
Perhaps also upgrading the libyui stack in Fedora may yield improvements. I'm not sure how far behind it is from upstream, but I know historically upstream was bad about tagging releases (which made it difficult for anyone to know if there was new code to pull in...)

**Comment by anaselli** [comment] 2019-12-10 13:52
Well i should have some days off for Christmas... so I would like to have something more concrete than a hope.... let's hope 😅

**Comment by anaselli** [comment] 2020-01-02 14:27
Please start testing [dnfdragora async branch](https://github.com/manatools/dnfdragora/tree/dnfdragora-async) i need  feedbacks  before merging it to master.
There are known regressions yet that I'm working on, but I need to know if there are blocking things that i'm missing...
I currently tested some concurrent running of dnfdragora-update and dnfdragora, either from dnfdragora-update or separately, and i seem not to have any crashes right now 
**Note** I haven't tested it in fedora yet so i expect crashes on group caching and maybe other things related to comp and fedora explicitly. I will do some test for it later when i fixed common things first

**Comment by Conan-Kudo** [comment] 2020-02-02 00:28
The async branch has been merged into master, so please test from master now. :)

**Comment by anaselli** [comment] 2020-05-30 14:59
With new implementation let's close this issue. Feel free to open new ones if experienced any problems, thanks.

**Closed by anaselli** 2020-05-30 14:59 UTC
