### ISSUE TITLE
Crash after clicking a link in the package description

### ISSUE THREAD

**Issue by fschaupp** [manatools/dnfdragora#239] opened 2024-11-18 16:27 UTC
Clicking those links in the update notes doesn't open them in the system browser.
It currently just crashes the program.
![grafik](https://github.com/user-attachments/assets/3c9ec79d-f392-43cd-a7d5-9aaa80f7bfbf)

I reported the issue on the fedora bugtracker via the error reporting tool:
https://bugzilla.redhat.com/show_bug.cgi?id=2327018
https://bugzilla.redhat.com/show_bug.cgi?id=2283118
https://bugzilla.redhat.com/show_bug.cgi?id=2262007

**Comment by anaselli** [comment] 2024-11-20 19:44
Sorry ti seem that we have already fixed and this is a duplicate of #217.
Fixed in this [commit](https://github.com/manatools/dnfdragora/commit/abbe08b7a487325182758d5285b54437a914207b)  and in release [2.1.6](https://github.com/manatools/dnfdragora/releases/tag/2.1.6)

**Closed by anaselli** 2024-11-20 19:44 UTC

**Comment by fschaupp** [comment] 2024-11-20 19:56
Oh, thank you :3
Seems like Fedora Cinnamon haven't updated it since...
