### ISSUE TITLE
dnfdragora-updater doesn't create "updates available" notification when it is runs on system boot, but it does when it is run manually.

### ISSUE THREAD

**Issue by gorkoda1** [manatools/dnfdragora#134] opened 2019-04-21 11:47 UTC
dnfdragora-updater doesn't create "updates available" notification when it is runs on system boot on Fedora 29 MATE, but it does when it is run manually, or if the user logs out and logs back in.  
output of `dnfdragora --version`
`dnfdragora  
version: 1.1.1  
site: https://github.com/manatools/dnfdragora  `
`/etc/dnfdragora/dnfdragora.yaml` contains `update_interval: 180`
EDIT: i tried a fresh fedora mate install and it seems to work. not sure why it's happening on my machine though.

**Comment by anaselli** [comment] 2019-04-21 19:26
If you reduce that time to 10 or 20 minutes does it happen or gives the updates after about 10 or 20 minutes later on boot?

**Comment by gorkoda1** [comment] 2019-04-22 13:30
@anaselli it doesn't. however i modified startup application in mate so that when dnfdragora-updater was launched at startup it would launch inside a terminal. this is an extra error message that i got: `Exception caught: [org.freedesktop.DBus.Error.ServiceUnknown: The name :1.66 was not provided by any .service files]`

**Comment by anaselli** [comment] 2019-04-22 13:39
As far as i remember it shouldn't launch any services... just connect to dnfdaemon as client

**Comment by gorkoda1** [comment] 2019-04-22 13:56
>just connect to dnfdaemon as client    

doesn't connecting to dnfdaemon create it? when i run systemctl status dnfdaemon when dnfdragora isn't running it's says that it is inactive and i can't find it in mate-system-monitor, however when dnfdragora is running i can find it and systemctl says that it is active, but only if dnfdragora is started manually.  
i'll try restarting my computer and if i find anything i'll let you know.

**Comment by gorkoda1** [comment] 2019-04-22 14:02
ok i restarted my computer and it turns out dnfdaemon does start. after the error message is outputted dnfdaemon becomes inactive.

**Comment by anaselli** [comment] 2019-04-22 14:36
Correct, dnfdaemon is invoked by client connection, but it's hidden to dnfdragora code, so if the daemon startup fails, it should be elsewhere, maybe.  What sounds very odd to me is the service name (:1.66) that seems to be a wrong string concatenation... but i don't know where

**Comment by gorkoda1** [comment] 2019-04-25 13:44
I should also note: the tray icon is not created ether.

**Comment by aureoud-fr85** [comment] 2020-07-27 09:13
This issue seems to be not present on Mageia Cauldron (mga8 alpha1) with 2.0.4 version and on Plasma 5.19.3.

dnfdragora displays correct notification at user log on and when manually selecting "Look for update" in right-click menu, if updates are available. I will look forward next couple days if it will display notifications when new updates will be available.

**Comment by aureoud-fr85** [comment] 2020-07-27 15:18
I reproduce some misbehaving today with current version 2.0.4 in Cauldron.
By default, in Mageia, legacy but functioning mgaapplet looks for updates 5 minutes after a system boot and user logs on.
But when updates are available here, dnfdragora-updater applet does nothing. I know it is independent from urpmi-tools, but  even pressing "Look for updates" in right-click menu does not give any return.
I simultaneously checked "journalctl -f" command: there is some success in background but no graphical output.
Here is output
[code=bash]
systemd[1]: Starting dnf makecache...
dbus-daemon[862]: [system] Successfully activated service 'org.baseurl.DnfSystem'
dnf[40125]: Mageia Cauldron - x86_64                        8.0 kB/s | 2.5 kB     00:00
dnf[40125]: Mageia Cauldron - x86_64                         40 MB/s |  38 MB     00:00
dnf[40125]: Mageia Cauldron - x86_64 - Updates              5.8 kB/s | 1.5 kB     00:00
dnf[40125]: Mageia 8 - x86_64                               496  B/s |  51  B     00:00
dnf[40125]: Error: Échec du téléchargement des métadonnées pour le dépôt « mageia-x86_64 » : Cannot prepare internal mirrorlist: No URLs in mirrorlist
dnf[40125]: Mageia 8 - x86_64 - Updates                     537  B/s |  51  B     00:00
dnf[40125]: Error: Échec du téléchargement des métadonnées pour le dépôt « updates-x86_64 » : Cannot prepare internal mirrorlist: No URLs in mirrorlist
dnf[40125]: Dépôts ignorés : mageia-x86_64, updates-x86_64
dnf[40125]: Cache des métadonnées créé.
systemd[1]: dnf-makecache.service: Succeeded.
systemd[1]: Finished dnf makecache.
systemd[1]: dnf-makecache.service: Consumed 9.003s CPU time.
[/code]
Error checking Mageia 8 depot is normal, it is Cauldron, not mga8 which is not published.
There are no other errors. dnf query are reported successful but there is no graphical notifications.

Also, there is any notification when there are no updates. 

Default intervals query are 180 minutes to look for updates and 48 hours for metadatas.

**Comment by anaselli** [comment] 2020-07-27 15:49
it isn't clear to me, does dnfdragora show updates or not? I mean no notifications but there updates in dnfdragora? (test is not meant to see different behavior with rpmdrake and mga applet)

**Comment by anaselli** [comment] 2020-07-27 15:59
> But when updates are available here, dnfdragora-updater applet does nothing. I know it is independent from urpmi-tools, but even pressing "Look for updates" in right-click menu does not give any return.

that probably mean that dnfdragora-update is trying to sync metadata, i experienced a very slow download when mirrors update metadata... you could enable logging options (you should know how to do it from user settings) with debug level... that helps a lot... maybe also reach us on IRC  #manatools channel

**Comment by Conan-Kudo** [comment] 2020-07-27 16:23
```
dnf[40125]: Error: Échec du téléchargement des métadonnées pour le dépôt « mageia-x86_64 » : Cannot prepare internal mirrorlist: No URLs in mirrorlist
dnf[40125]: Mageia 8 - x86_64 - Updates 537 B/s | 51 B 00:00
dnf[40125]: Error: Échec du téléchargement des métadonnées pour le dépôt « updates-x86_64 » : Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

This shows that there's a problem on the Mageia infrastructure side causing mirrorlists to not be populated with any mirrors.

**Comment by Conan-Kudo** [comment] 2020-07-27 16:24
@aureoud-fr85 What does `dnf --refresh --assumeno upgrade` print out?

**Comment by aureoud-fr85** [comment] 2020-07-27 18:11
I checked logging in dnfdragora.
I managed to wait for real update. By chance, mgaapplet tells me there is initscripts-9.78-20.mga8 available.
Because I think metadatas were considered fresh (renew every 48 hours by default) and I also think that it was between the 180 minutes grace period when dnfdaemon look for update.
So right after I do several tests:
1) I launch dnfdragora: refreshing metadatas upon launching it, I get update available within dnfdragora UI.
2) No notification for update in tray as it is displayed in dnfdragora. 
3) Closing dnfdragora without applying the update. Right after, notification is displayed.
4) Click "Look for updates" in right click menu of dnfdragora-updater applet => notification displayed.
5) Log out then log in my session: => notification displayed.
Updating my system.
6) Click "Look for updates" => no notification. UI does not inform user there is no update.

here is dnfdragora.log:
[dnfdragora.log](https://github.com/manatools/dnfdragora/files/4983745/dnfdragora.log)
[dnfdragora-updater.log](https://github.com/manatools/dnfdragora/files/4983748/dnfdragora-updater.log)

**Comment by aureoud-fr85** [comment] 2020-07-27 18:19
> @aureoud-fr85 What does `dnf --refresh --assumeno upgrade` print out?

dnf --refresh --assumeno upgrade
Mageia Cauldron - x86_64                                                                                                     9.6 kB/s | 2.5 kB     00:00    
Mageia Cauldron - x86_64 - Updates                                                                                           2.4 kB/s | 1.5 kB     00:00    
Mageia 8 - x86_64                                                                                                            485  B/s |  51  B     00:00    
Error: Échec du téléchargement des métadonnées pour le dépôt « mageia-x86_64 » : Cannot prepare internal mirrorlist: No URLs in mirrorlist
Mageia 8 - x86_64 - Updates                                                                                                  480  B/s |  51  B     00:00    
Error: Échec du téléchargement des métadonnées pour le dépôt « updates-x86_64 » : Cannot prepare internal mirrorlist: No URLs in mirrorlist
Dépôts ignorés : mageia-x86_64, updates-x86_64
Dépendances résolues.

 Paquet                               Architecture                    Version                                 Dépôt                                    Taille
Mise à jour:
 initscripts                          x86_64                          9.78-20.mga8                            cauldron-x86_64                          1.1 M

Résumé de la transaction
Mettre à niveau  1 Paquet
Taille totale des téléchargements : 1.1 M
Opération avortée.

@Conan-Kudo : I think it is normal that there errors for potential mageia 8 repos : they don't exists as 8 is not published.
But urpmi does not display such errors. I wonder why they are set. I installed this version of cauldron with Mageia 8 alpha 1 ISO (Classic Installer) with Plasma 5.19 desktop.

**Comment by anaselli** [comment] 2020-07-27 19:58
> I managed to wait for real update. By chance, mgaapplet tells me there is initscripts-9.78-20.mga8 available.

But mgaapplet works differently, I for instance added skype using dnf so it is never seen by mgapplet as updates

> Because I think metadatas were considered fresh (renew every 48 hours by default) and I also think that it was between the 180 minutes grace period when dnfdaemon look for update.

metadata expire from time to time (maybe @Conan-Kudo  can say more and better here) and that does not depend on your configuration, 180 minutes are for looking for updates but it does not necessay refresh metadata so that could result in no updates. But here you know there are, so you forced a refresh and then you've seen them.
Despite of that a metadata refresh is performed by using second configuration parameter e.g. the metadata  update_interval, that is in hours (48 as default iirc e.g. two days) and that is called in tha options dialog as _Metadata expire time_.

>     1. I launch dnfdragora: refreshing metadatas upon launching it, I get update available within dnfdragora UI.

the problem here is that the metadata download and caching time is performed by dnfdragora and not dnfdragora-update, so as soon as finished you should have the notify.

>     2. No notification for update in tray as it is displayed in dnfdragora.

Right, only one can run, update silently wait for locking the db.

>     3. Closing dnfdragora without applying the update. Right after, notification is displayed.

indeed
 
>     4. Click "Look for updates" in right click menu of dnfdragora-updater applet => notification displayed.

correct, you forced a check and you know there are and metadata are refreshed too.
 
>     5. Log out then log in my session: => notification displayed.

Good it's working then

>        Updating my system.
>     6. Click "Look for updates" => no notification. UI does not inform user there is no update.

There is no notification for 0 updates, honestly i wanted to remove the icon but that seems not to work well, next notification wil not show the dnfdragora-update icon that is worst.

I seem it works correctly. Where is the problem?

**Comment by aureoud-fr85** [comment] 2020-07-27 20:08
> There is no notification for 0 updates, honestly i wanted to remove the icon but that seems not to work well, next notification wil not show the dnfdragora-update icon that is worst.
> 
> I seem it works correctly. Where is the problem?

In fact, as we cannot remove the icon, why can we just display "No update available" when user has selected "Check for Update" in right-click menu?
Not displaying anything when there is no update can confuse the user that something in background is crashed or not responsive.

**Comment by anaselli** [comment] 2020-07-27 20:59
it would seem a good compromise in the mean while yes. Will think about it...

**Closed** 2020-08-02 17:51 UTC
